embedding_dim: 64
vocab_size: 20
tau: 2.0
epochs: 30
batch_size: 32
lr: 0.001
n_samples: 3000
time_stride: 10      # distanza temporale tra immagine e parola associata
noise_std: 0.1       # intensità del rumore gaussiano sulle immagini
digits: [3, 6, 9]